language: python
python:
    - 3.6
before_install:
    - pip install -U pip
    - pip install -r requirements.txt
install:
    - pip install -e .
script:
    - flake8 diffkemp_htmlgen
    - flake8 tests --ignore=E501,F403,F405
    - mypy --strict diffkemp_htmlgen
    - python -m pytest tests
